#11111B
#725AC1
#8D86C9
#CAC4CE
#F7ECE1

background = "#11111B"

[[slides]]

  [[slides.widgets]]
  
  type = "animatedCircleSectionLines"
  centerAngle = 225
  offsetAngle = 45

  x = 45
  y = 45

  radius = 40
  thickness = 5
  colour = "#F7ECE1"
  easeType = "In"
  speed = 2

    [[slides.widgets.children]]
    type = "animatedRect"
    x = 40
    y = 0
    width = 1745
    height = 5
    orientation = "right"
    colour = "#F7ECE1"
    easeType = "Out"
    speed = 0.5

    [[slides.widgets.children]]
    type = "animatedRect"
    x = 0
    y = 40
    width = 5
    height = 905
    colour = "#F7ECE1"
    easeType = "Out"
    orientation = "down"
    speed = 0.5

  [[slides.widgets.children]]
  
  type = "animatedCircleSectionLines"
  centerAngle = 135
  offsetAngle = 45

  x = 0
  y = 905

  radius = 40
  thickness = 5
  colour = "#F7ECE1"
  easeType = "InOut"
  speed = 1

  [[slides.widgets]]

  type = "animatedCircleSectionLines"
  centerAngle = 45
  offsetAngle = 45

  x = 1790
  y = 950

  radius = 40
  thickness = 5
  colour = "#F7ECE1"
  easeType = "In"
  speed = 2

    [[slides.widgets.children]]
  
    type = "animatedCircleSectionLines"
    centerAngle = 315
    offsetAngle = 45

    x = 0
    y = -905

    radius = 40
    thickness = 5
    colour = "#F7ECE1"
    easeType = "InOut"
    speed = 1
  
    [[slides.widgets.children]]
    type = "animatedRect"
    x = -1705
    y = 75
    width = 1750
    height = 5
    colour = "#F7ECE1"
    easeType = "Out"
    orientation = "left"
    speed = 0.5

    [[slides.widgets.children]]
    type = "animatedRect"
    x = 75 
    y = -865
    width = 5
    height = 905
    colour = "#F7ECE1"
    easeType = "Out"
    orientation = "up"
    speed = 0.5

  [[slides.widgets]]
  type = "animatedText"

  colour = "#F7ECE1"
  size = 100
  x = 960
  y = 540
  contents = "Farenheit 451"

  style = "body"

  [[slides.widgets]]
  type = "animatedText"

  colour = "#CAC4CE"
  size = 50
  x = 960
  y = 640
  contents = "By Gavin D."

  style = "body"

[[slides]]
  
  [[slides.widgets]]
  type = "animatedImage"
  source = "./resources/test.jpg"
  direction = "left"
  speed = 1
  x = 0
  y = 0
