#11111B
#725AC1
#8D86C9
#CAC4CE
#F7ECE1
background = "#11111B"
[[slides]]

  [[slides.widgets]]
  
  type = "animatedCircleSectionLines"
  centerAngle = 225
  offsetAngle = 45

  x = 25
  y = 25

  radius = 40
  thickness = 5
  colour = "#F7ECE1"
  easeType = "In"
  speed = 2

    [[slides.widgets.children]]
    type = "animatedRect"
    x = 40
    y = 0
    width = 1150 
    height = 5
    orientation = "right"
    colour = "#F7ECE1"
    easeType = "Out"
    speed = 0.5

    [[slides.widgets.children]]
    type = "animatedRect"
    x = 0
    y = 40
    width = 5
    height = 670
    colour = "#F7ECE1"
    easeType = "Out"
    orientation = "down"
    speed = 0.5

  [[slides.widgets.children]]
  
  type = "animatedCircleSectionLines"
  centerAngle = 135
  offsetAngle = 45

  x = 0
  y = 670

  radius = 40
  thickness = 5
  colour = "#F7ECE1"
  easeType = "InOut"
  speed = 1

  [[slides.widgets]]

  type = "animatedCircleSectionLines"
  centerAngle = 45
  offsetAngle = 45

  x = 1175
  y = 695

  radius = 40
  thickness = 5
  colour = "#F7ECE1"
  easeType = "In"
  speed = 2

    [[slides.widgets.children]]
  
    type = "animatedCircleSectionLines"
    centerAngle = 315
    offsetAngle = 45

    x = 0
    y = -670

    radius = 40
    thickness = 5
    colour = "#F7ECE1"
    easeType = "InOut"
    speed = 1
  
    [[slides.widgets.children]]
    type = "animatedRect"
    x = -1110
    y = 75
    width = 1150
    height = 5
    colour = "#F7ECE1"
    easeType = "Out"
    orientation = "left"
    speed = 0.5

    [[slides.widgets.children]]
    type = "animatedRect"
    x = 75 
    y = -630
    width = 5
    height = 670
    colour = "#F7ECE1"
    easeType = "Out"
    orientation = "up"
    speed = 0.5

  [[slides.widgets]]
  type = "text"

  colour = "#F7ECE1"
  size = 100
  x = 640
  y = 400
  contents = "Farenheit 451"

  style = "body"

  [[slides.widgets]]
  type = "text"

  colour = "#CAC4CE"
  size = 50
  x = 640
  y = 540
  contents = "By Gavin D."

  style = "body"

[[slides]]

  [[slides.widgets]]
  type = "animatedText"
  contents = "What do you do that makes you happy?"
  size = 60
  style = "body"
  speed = 4
  colour = "#F7ECE1"
  x = 640
  y = 400

  [[slides.widgets.children]]
  type = "animatedRect"
  colour = "#725AC1"
  x = -415
  y = 10
  width = 55
  height = 10
  orientation = "right"

    [[slides.widgets.children]]
    type = "animatedText"
    colour = "#F7ECE1"
    x = 0
    y = 100
    size = 50
    easeType = "InOut"
    speed = 0.50
    contents = "What do you create that you enjoy?"

      [[slides.widgets.children.children]]
      type = "animatedRect"
      colour = "#725AC1"
      x = -320 
      y = 0
      width = 40
      height = 0.2
      orientation = "left"
      
      [[slides.widgets.children.children]]
      type = "animatedSpacer"
      x = 0
      y = 0
      width = 0
      height = 0

      speed = 0.33

        [[slides.widgets.children.children.children]]
        type = "animatedText"
        colour = "#F7ECE1"
        x = 0
        y = -200
        size = 75
        easeType = "InOut"
        speed = 0.50
        contents = "Do you create anything?"

  [[slides.widgets]]
  type = "animatedCircle"
  x = 0
  y = 0
  width = 1
  colour = "#11111B"
  speed = 0.1
  radius = 1
  height = 0.1

    [[slides.widgets.children]]
    type = "animatedRect"
    x = 0
    y = 0
    width = 1920
    height = 1920
    colour = "#11111B"
    speed = 0.4

      [[slides.widgets.children.children]]
      type = "animatedImage"
      source = "./resources/flame.jpg"
      x = 413
      y = 177
      speed = 0.7
      scale = 4

      [[slides.widgets.children.children]]
      type = "animatedImage"
      source = "./resources/StackOfBooks.png"
      x = 980
      y = 500
      scale = 0.5
      speed = 0.4

[[slides]]

  [[slides.widgets]]
  type = "animatedText"
  contents = "all of this to say:"
  colour = "#F7ECE1"
  size = 40
  x = 640
  y = 200

    [[slides.widgets.children]]
    type = "animatedImage"
    source = "./resources/brain.png"
    x = -238
    y = 100
    scale = 1.5

  [[slides.widgets]]
  type = "animatedCircle"
  x = 0
  y = 0
  width = 1
  colour = "#11111B"
  speed = 0.5
  radius = 1
  height = 1

    [[slides.widgets.children]]
    type = "animatedRect"
    x = 0
    y = 0
    width = 1920
    height = 1920
    colour = "#11111B"
    speed = 0.4

      [[slides.widgets.children.children]]
      type = "animatedText"
      x = 640
      y = 150
      size = 50
      colour = "#F7ECE1"
      contents = "What's Bradbury trying to say?"

      [[slides.widgets.children.children]]
      type = "animatedCircle"
      x = 0
      y = 0
      radius = 1
      colour = "#11111B"
      speed = 0.3

        [[slides.widgets.children.children.children]]
        type = "animatedRect"
        orientation = "left"
        x = 100
        width = 1080
        y = 100
        height = 100
        colour = "#F7ECE1"


### THEME STATEMENT
[[slides]]

  [[slides.widgets]]
  type = "rect"
  x = 100
  width = 1080
  y = 100
  height = 100
  colour = "#F7ECE1"

  [[slides.widgets]]

  type = "animatedRect"
  x = 110
  width = 1060
  y = 110
  height = 80
  colour = "#11111B"
  orientation = "right"


    [[slides.widgets.children]]
    type = "animatedText"
    x = 570
    y = 400
    size = 40
    contents = "How does the book support this theme?"
    colour = "#F7ECE1"

  [[slides.widgets]]

  type = "text"
  x = 640
  y = 170
  colour = "#F7ECE1"
  size = 50
  contents = "Without growth one can't be happy."

### a bunch of quotes
[[slides]]

  [[slides.widgets]]
  type = "animatedRect"
  x = 1133
  y = 74
  width = 10
  height = 333
  colour = "#F7ECE1"
  easeType = "In"

    [[slides.widgets.children]]
    type = "animatedRect"
    x = 0
    y = 333
    width = 10
    height = 333
    colour = "#F7ECE1"
    easeType = "Out"

    [[slides.widgets.children]]
    type = "animatedRect"
    x = -666 
    y = 333
    width = 666
    height = 10
    colour = "#F7ECE1"
    orientation = "left"
    easeType = "In"

      [[slides.widgets.children.children]]
      type = "animatedRect"
      x = 0 
      y = 0
      width = 10
      height = 296
      colour = "#F7ECE1"
      orientation = "down"
      easeType = "Out"

      [[slides.widgets.children.children]]
      type = "animatedRect"
      x = -450 
      y = 0
      width = 450
      height = 10
      colour = "#F7ECE1"
      orientation = "left"
      easeType = "Out"

  [[slides.widgets]]
  type = "animatedText"
  # p 58 "beatty's rant"
  size = 20
  colour = "#F7ECE1"
  x = 500
  y = 250
  contents = """
"Give the people contests they win by remembering the words to more 
popular songs or names of state capitals or how much corn Iowa grew last year. 
Cram them full of noncombustible data, chock them so damned full of 
'facts' they feel stuffed, 
but absolutely 'brilliant' with information. 
Then they'll feel they're thinking, 
they'll get a sense of motion without ever actually moving. 
And they'll be happy, 
because facts of that sort don't change. 
Don't give them any slippery stuff 
like philosophy or sociology to tie things up with. 
That way lies meloncholy." (58)
  """ 

    [[slides.widgets.children]]
    type = "animatedText"
    contents = """
    this reminds me about y'know
    of like... a lot of content running quickly
    of which can have "information"
    but not really information that means anything
    """
    x = 300
    y = 333
    size = 20
    speed = 0.3
    colour = "#F7ECE1"

      [[slides.widgets.children.children]]
      type = "animatedImage"
      source = "./resources/instagram.png"
      x = -666
      y = -125 
      scale = 0.5 
      speed = 0.15
  
  [[slides.widgets]]
  type = "animatedCircle"
  x = 0
  y = 0
  radius = 1
  colour = "#11111B"
  speed = 0.05

    [[slides.widgets.children]]
    type = "animatedRect"
    x = 0
    y = 0
    width = 1280
    height = 800
    colour = "#11111B"
    speed = 0.4

[[slides]]

  [[slides.widgets]]
  type = "animatedRect"
  x = 50
  y = 100
  width = 10
  height = 300
  colour = "#F7ECE1"
  easeType = "In"

    [[slides.widgets.children]]
    type = "animatedText"
    contents = """
    'I hate a Roman named Status Quo!' he said to me. 
    'Stuff your eyes full of wonder,' he said, 
    '... See the world. 
    It's more fantastic than any dream made or paid for in factories... 
    [otherwise you'll] be related to the great sloth 
    which hangs upside down in a tree all day every day, 
    sleeping its life way, to hell with that,' he said, 
    'shake the tree and knock the great sloth down on his ass.'
    (150)
    """
    size = 25
    colour = "#F7ECE1"
    x = 500
    y = 160

    [[slides.widgets.children]]
    type = "animatedRect"
    x = 0
    y = 300
    width = 300
    height = 10
    easeType = "Out"
    orientation = "right"
    colour = "#F7ECE1"


      [[slides.widgets.children.children]]
      type = "box"
      orientation = "horizontal"
      x = 300
      y = 0

        [[slides.widgets.children.children.widgets]]
        type = "animatedRect"
        x = 300
        y = 0
        width = 10
        height = 300
        easeType = "InOut"
        orientation = "down"
        colour = "#F7ECE1"

        [[slides.widgets.children.children.widgets]]
        type = "animatedSpacer"
        x = 0
        y = 0
        width = 100
        height = 300
        orientation = "right"

        [[slides.widgets.children.children.widgets]]
        type = "animatedImage"
        x = 0
        y = 600
        easeType = "InOut"
        orientation = "right"
        source = "./resources/sloth.jpg"
        colour = "#F7ECE1"
        scale = 0.500

[[slides]]

  [[slides.widgets]]
  type = "animatedText"
  contents = """
  "Can you dance faster than the White Clown, 
  shout louder than 'Mr. Gimmick' 
  and the parlor 'families'? 
  If you can, you'll win your way, Montag. 
  In any event, you're a fool. 
  People are having fun,"
  (83)
  """
  x = 640
  y = 400
  size = 30
  colour = "#F7ECE1"

    [[slides.widgets.children]]
    type = "animatedText"
    x = 0
    y = 300
    speed = 0.3
    size = 25
    contents = "They're having fun, but they aren't happy"
    colour = "#CAC4CE"

  [[slides.widgets]]
  type = "animatedRect"
  x = 240
  y = 260
  width = 10
  height = 220
  colour = "#8D86C9"
  speed = 2

#### ENDING SLIDE
[[slides]]

  [[slides.widgets]]
  type = "animatedText"
  x = 200
  y = 50
  size = 50
  contents = "Ending notes"
  colour = "#F7ECE1"

  [[slides.widgets]]
  type = "animatedText"
  x = 640
  y = 400
  size = 20

  speed = 0.3
  contents = """
  This slideshow was made in a custom engine.
  If you want to see the source it's visible at 
  https://github.com/maningreen/slideShow
  If you wish to clone the source, you can with the command 
  `git clone https://github.com/maningreen/slideShow.git`
  This software is licensed under the MIT license, as such you can use this in a closed source project.
  sources for images can be found at ./resources/sources.md
  All the software used to create this are free and open source.
  Thank you for your time and get off your phone, go fill your eyes with wonder,
  beauty isn't mass produced.
  I should've added better slide transitions.
  """
  colour = "#F7ECE1"

  [[slides.widgets]]
  type = "animatedText"
  x = 500
  y = 700
  size = 20

  contents = """
  No "generative AI" wrote any of the content in this presentation
  frontend or backend
  """
  speed = 0.3
  colour = "#F7ECE1"
